Algoritmo "parouimpar"
// Disciplina  : Tecnicas de programação
// Professor   : Tiago e Luis Eduardo
// Descrição   : Quadrado de quatro numeros
// Autor(a)    : Gabriel Loureiro Amorim Hugi
// Data atual  : 18/03/2024
//
Var
N, R: Inteiro

Inicio

      Escreva("Insira um numero")
      Leia(N)
      R <- (N mod 2)
      se(R=0) então
      Escreval(N, "é um numero par")
      senao
      Escreval(N, " é um numero impar")
      fimse



Fimalgoritmo